apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster3-myapps-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ns1
    name: in-cluster
  project: default
  source:
    path: cluster3/myapps/ns1
    repoURL: https://github.com/bahmanzadeh/argocd-test.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true