apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster3-myapps
  namespace: default
spec:
  generators:
  - git:
      directories:
      - path: cluster3/myapps/*
      repoURL: https://github.com/bahmanzadeh/argocd-test.git
      revision: HEAD
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: https://192.168.122.198:8443
      project: myapps
      source:
        path: '{{path}}'
        repoURL: https://192.168.122.198:8443
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
        - FailOnSharedResource=true
        - ApplyOutOfSyncOnly=true
